### ISSUE TITLE
Switch to self-hosting cljs

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/clojurescript-koans#10]
When I build this, cljs wasn't self-hosted. As a result, it currently exists as a very fragile hack whereby there are two parallel cljs stacks existing in the browser at the same time: a modern (at the time) one, and a hacky, old, mostly-functioning self-hosted fork that existed purely to do in-browser execution of user code.

Now that CLJS is itself properly self-hosting, this can be simplified greatly.

**Comment by mkremins** [comment]
Fixed this as of 00b375fb8f41d59ffb566a6470965c40207b2e8c.
