### ISSUE TITLE
I am unable to run clojurescript koans in Firefox under Ubuntu 64bit

### ISSUE THREAD

**Issue by jared83** [lazerwalker/clojurescript-koans#11]
Actually I am using KXStudio with KDE on top which is based on Ubuntu 64bit.
Firefox version is 41.0.2
When I go to the first koan (http://clojurescriptkoans.com/#equality/1) all I can see is the koans logo image (painted circle).
"View source" shows exactly the came code as in Chrome.
The inspector in Chrome shows body with  id="dummybodyid" and nested I can see the koan
```html
 <div class="koan koan-0" style="display: block;">...</div>
```
all works fine.
In Firefox however, the id="dummybodyid" is missing from the body, and so is the koan.
The next div in chrome:
```html
 <div class="category" style="display: block;">equality</div>
```
The same div in Firefox:
```html
    <div class="category"></div>
```
...empty, nothing.
All looks as if clojurescript isn't running at all, yet all clojurescript files downloaded just fine.
FireBug shows this:
```html
-> uncaught exception: Invalid match arg: /\(quote (.*?)\)/ <unknown>
-> This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] connect.facebook.net
-> Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:2:0
``` 
Any clue what's going on? Instinct tells me it's the uncaught exception's fault
cheers
Jared

**Comment by lazerwalker** [comment]
I'm now experiencing similar behavior (but different inspector messages) in Safari on OS X. 

Will poke into this at some point, but my suspicion is that whatever's causing this would ultimately be solved by https://github.com/lazerwalker/clojurescript-koans/issues/10, as the most likely cause of anything like this is how completely janky the current cljs setup is (there are two parallel cljs stacks running in the browser, one "modern" 2-year-old cljs serving the app itself and an even older unsupported self-hosting fork that exists purely to evaluate code).

Thanks!

**Comment by lazerwalker** [comment]
Trying to consolidate tracking this issue in #13, so going to close this.
