### ISSUE TITLE
Koans do not load in many browsers

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/clojurescript-koans#13]
The koans now seem completely nonfunctioning to me in Safari, both on OS X (10.11) and iOS (9.1).

Here's the stack trace for the error I get on any page:

<img width="253" alt="screen shot 2015-11-27 at 11 29 44" src="https://cloud.githubusercontent.com/assets/821238/11445474/5baf858a-94fa-11e5-9c67-4a94840d0e05.png">

This is likely related to #11. Although I could investigate this on its own, it might be worth waiting until #10 happens, both because the problem might fix itself and because dealing with outdated tooling might turn out to be a major pain.

**Comment by mheiber** [comment]
I'm seeing the same thing in Chrome

**Comment by nashio** [comment]
I can reproduce this on Firefox 43.0.4  and Chrome Canary
but  on Chrome 47, its working fine

**Comment by Krajsnick** [comment]
Same for me using Safari 9.0.3 on OSX 10.11.3

**Comment by lazerwalker** [comment]
Of the emails I've received, one claimed they could reproduce this with firefox 43.0.4 and chrome canary, but it worked fine on "regular" Chrome.

**Comment by lazerwalker** [comment]
Hey all who've chimed in on this, opened similar issues, or emailed me:

I'm sorry I've been so sluggish responding to all of these; I honestly (and heart-breakingly) haven't had, and won't really have, the time to really figure out what's going on here. I've updated the README to indicate I'm looking for someone who might be interested in helping.

https://github.com/lazerwalker/clojurescript-koans/blob/master/README.md#looking-for-maintainer

**Comment by aklt** [comment]
Hi,

I dug into issue #15 and found the reason for those troubles.  It turns out
that testing if `match` is a RegExp using `.hasOwnProperty('source')` always 
returns false and that this was a bug in ClojureScript:

    http://dev.clojure.org/jira/browse/CLJS-1304

So maybe an update to the latest ClojureScript would fix this. 
The current version does look quite ancient...

**Comment by mkremins** [comment]
Hi all,

After talking with @lazerwalker, I've ported the koans to the modern self-hosting ClojureScript compiler (as per #10) and removed the dependency on cljs-in-cljs. This necessarily involved updating the project to the latest ClojureScript, which (I think) fixed this issue as a side effect. If you're still having this problem, let me know!

Next steps from here: I'd like to address the currently-painful page load time (probably by switching to `:optimizations :simple` for the production build) and fix some of the other open issues on this repository.

**Comment by aklt** [comment]
And it's working again, great!

**Comment by nashio** [comment]
Working here too :D
