### ISSUE TITLE
clojurescriptkoans.com : Uncaught Invalid match arg: /\(quote (.*?)\)/

### ISSUE THREAD

**Issue by aklt** [lazerwalker/clojurescript-koans#15]
This exception is thrown whenever I try to begin the koans on the url

    http://clojurescriptkoans.com/#equality/1

and also on other urls:

    http://clojurescriptkoans.com/#equality/3

I had no problems last week where I looked at the koans. 

Same error in chromium and firefox.

Here is a stacktrace from chromium:

replace (string.cljs:33)
expr_to_string (meditations.cljs:61)
expr_to_array (meditations.cljs:76)
koan_for_index (meditations.cljs:91)
render_current_koan (core.cljs:135)
(anonymous function) (core.cljs:173)
l (jquery.min.js:2)
c.fireWith (jquery.min.js:2)
v.extend.ready (jquery.min.js:2)
A (jquery.min.js:2)

**Comment by tsaiDavid** [comment]
Seeing the same thing here!

**Comment by lazerwalker** [comment]
We've been seeing this behavior a lot lately. Trying to consolidate conversation in #13, but would both of you mind chiming in what browser/OS/etc you're using?

Thanks!
