### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by roman01la** [lazerwalker/clojurescript-koans#16]
Hello! I'm building a website for ClojureScript learning resources in russian https://clojurescript.ru/. I really like ClojureScript Koans. Do you mind if I build a clone of it in russian?

**Comment by mkremins** [comment]
Hi! As the current maintainer, I definitely don't mind. I'll even add a link to the translation in the README if you let me know once you finish it.

**Comment by roman01la** [comment]
That's great! Thank you. I'll let you know. 😊

**Comment by roman01la** [comment]
Hi! Just want to let you know that translated version is live at https://clojurescript.ru/koans/

**Comment by mkremins** [comment]
I've added a link to the translation in the README – thanks!
