### ISSUE TITLE
higher order functions: http://clojurescriptkoans.com/#higher-order-functions/9

### ISSUE THREAD

**Issue by ljubad** [lazerwalker/clojurescript-koans#17]
(= 2400 (reduce (fn [a b] (* a b)) :_ [1 2 3 4]))

I am not sure how to solve this.

My workaround is:
> (= 2400 (reduce (fn [a b] (* a b)) (into [100] [1 2 3 4])))
true

... but with additional parentheses at the end.

Could you help me here?

**Comment by mkremins** [comment]
The trick is that `reduce` can take an additional argument – you don't have to limit yourself to just two. Try looking up the docs and you'll probably see what I mean.

**Comment by ljubad** [comment]
Ok found it: https://clojuredocs.org/clojure.core/reduce
`(= 2400 (reduce (fn [a b] (* a b)) 100 [1 2 3 4]))`
This is so called identity, initial or starting value...
tx
