### ISSUE TITLE
single quote symbol ' can be submitted instead of significant answers, and can pass

### ISSUE THREAD

**Issue by matiasmasca** [lazerwalker/clojurescript-koans#18]
I can pass some exercises put only a ' symbol or '(). 

When they have the following form: (= ___ ( bla bla bla))

**Comment by mkremins** [comment]
This is closely related to #7 and will probably be fixed in the same patch. At the moment, I think there's exactly three characters that can cause this problem: comma, single-quote, and backquote.

**Comment by honzabrecka** [comment]
Perhaps sanitization like this would solve the issue?

```clojure
(defn input-is-valid? [v]
  (nil? (re-matches #"['`, ]+" v))))

(filter valid-input? ["'", " ' ' ", " ' ' a", "`", "'()", "," ",,," ",   , , , ", "'`"])
; (" ' ' a" "'()")
```

**Comment by mkremins** [comment]
@honzabrecka The regex I ended up going with was slightly more complicated, but yeah, that's the general approach!
