### ISSUE TITLE
[BUG] List returned in higher-order-functions/7 where vector is expected

### ISSUE THREAD

**Issue by avocade** [lazerwalker/clojurescript-koans#42]
Maybe someone has commented on this before, but this is impossible to solve AFAIK :D 

http://clojurescriptkoans.com/#higher-order-functions/7

Should probably be using `mapv` instead?

```
(= [10 20 30] (mapv (fn [x] ) (filter (fn [x] ) [1 2 3 4 5 6 7 8])))
```

**Comment by mkremins** [comment]
Not a bug, AFAIK. Clojure treats sequential collections as equal [when they have equal items in the same order](https://clojure.org/guides/equality), and the intended solution to this koan works in my browser. Try `(= [1 2 3] '(1 2 3))` at your REPL to verify.
